=begin
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
=end

sum = 0											#set sum to 0
fib1 = fib2 = 1 								#Both the first fib number and second in the sequence are set to one.
 
while fib2 < 4_000_000							#While the fib number is less than 4_000_000..
  sum += fib2 unless b.odd?						# Take the second number in the fib sequence and add it to the sum if it's even.
  fib1, fib2 = fib2, fib1+fib2					# move up the fib sequence 2 numbers at a time, with each iteration fib2 becomes fib1 and the new fib2 is the sum of the previous values.
end
 
puts sum