/*	Each new term in the Fibonacci sequence is generated by adding the previous two terms.
   By starting with 1 and 2, the first 10 terms will be:

		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

		By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
		find the sum of the even-valued terms.

 */

public class Euler002 {
	public static void main(String[] args) {
		int sum = 0, i = 2;
		
		long[] fib = new long[50];
		fib[0] = 1; fib[1] = 2;
		
		while(true) {
			fib[i] = fib[i-1] + fib[i-2];
			System.out.println(fib[i]);
			if(fib[i] > 4000000) break;
			if (fib[i] % 2 == 0) {
				sum +=fib[i];
			}
			i++;
			
		}
		System.out.println("Sum is: " + sum );
		
	}
}
